
server:
  port: 8080


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://dzspbfmrubdqhq:865f754e9c9b97f4e8581f2ca774b79615b9d14a8d969bba027a272ea5a104f8@ec2-18-211-41-246.compute-1.amazonaws.com:5432/d4tgjmmb15fv4l
    username: dzspbfmrubdqhq
    password: 865f754e9c9b97f4e8581f2ca774b79615b9d14a8d969bba027a272ea5a104f8
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto TCC
  version: 1.0
