
server:
  port: 8080


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://pjfyjuqhwtsrwo:7a3e948598a8d60d5138de3e146aec845876d8d6781dbad37da4334a4a326bdb@ec2-3-89-0-52.compute-1.amazonaws.com:5432/d27dk3e38qd9lg
    username: pjfyjuqhwtsrwo
    password: 7a3e948598a8d60d5138de3e146aec845876d8d6781dbad37da4334a4a326bdb
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto TCC
  version: 1.0
